server {
    listen 80;
    server_name _; # Catch-all server name

    # Location for static files
    location /static/ {
        alias /app/staticfiles/; # Path to your collected static files
        expires 30d;
        add_header Cache-Control "public";
    }

    # Location for media files (if you have them)
    # location /media/ {
    #     alias /app/media/; # Path to your media files
    # }

    location / {
        proxy_pass http://127.0.0.1:8000; # Pass requests to Gunicorn
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
